name: Build

on:
  pull_request_target:
    types: [edited, opened, synchronize, reopened]

jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20

      - name: Fetch API data
        env:
          PRETIX_TOKEN: ${{ secrets.PRETIX_TOKEN }}
        run: bash ./data/fetch.sh

      - name: Build
        run: |
          nix build

      - name: Copy build result
        run: |
          cp -rv $(readlink -f result) out

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: out/**
